### ISSUE TITLE
JFT is not updated at the beginning of the day.

### ISSUE THREAD

**Issue by Connected57** [bmlt-enabled/fetch-jft#10]
**Describe the bug**

JFT does not update at the beginning of the day(12am PST). For example, today is March 13th and at 8am PST I checked JFT on my area website and it showed JFT for March 12th. I checked it again at 10am PST and it showed the correct JFT. 

**To Reproduce**
1. Go to https://naventuracounty.com/
3. Scroll down on the home page to the JFT section before 9am PST and again after 10am PST.

**Expected behavior**

I expect the JFT to start displaying at 12:00am PST not 10am PST

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

I accessed the WordPress dashboard and checked the timezone under Settings > General and it shows Los Angeles so it isn't a website timezone issue in my opinion.

[screencapture-naventuracounty-wp-admin-options-general-php-2022-03-13-11_13_30.pdf](https://github.com/bmlt-enabled/crouton/files/8240334/screencapture-naventuracounty-wp-admin-options-general-php-2022-03-13-11_13_30.pdf)

**Comment by alanb2718** [comment]
Could this be due to the server caching the page?  The https://naventuracounty.com/ site is showing yesterday's JFT right now, but on a couple of other sites it's up-to-date.  (Except https://www.crna.org/for-members/ which is March 12 .... hmm ...).

To test this, @Connected57 on your server could you flush any caches, and see what happens?

**Comment by pjaudiomv** [comment]
One of the issues that may be at play is that the plugin just scrapes the jftna.org site and i believe the jft gets updated around 10pm PST or sometime around there so there will def be times when its not right. My plan is to create a proper jft api, however when I reached out to naws they gave me permission to scrape the site. So I will either have to reach back out to naws and get permission to store the data in an api or get a service body to adopt and host the api. I have slowly been working on the pieces needed for this.

**Comment by pjaudiomv** [comment]
oh that is weird, yea crna.org is def caching it. I broke the cache and its updated https://www.crna.org/for-members/?v=3

**Comment by pjaudiomv** [comment]
im closing this as nothing really I can do in plugin to prevent this. The pages in which fetch jft is used on should be added to exception in caching provider
