### ISSUE TITLE
New Plugin ?

### ISSUE THREAD

**Issue by Connected57** [bmlt-enabled/fetch-jft#16]
Hi,
I don't have an issue, but this is the only way I come up with to ask a question. Now that we have our new piece of literature (A Spiritual Principal A Day) out are there any future plans to create a plugin like fetch-jft for A Spiritual Principal A Day (ASPAD)? My Public Relations Sub-Committee wanted me to ask as we already use fetch-jft on our website and would love to have ASPAD on our site as well. 

Kind Regards,
Aaron H.
[Gold Coast Area](https://naventuracounty.com/) Webmaster

**Comment by pjaudiomv** [comment]
Hi Aaron,

Yes there is a plan for a separate  plugin for SPAD. We are currently waiting for NAWS to release a spad site similar to jftna.org. Whenever they do this we will release a plugin. I am not sure of any time from NAWS has for this right now.

Patrick J
Fetch JFT Maintainer
BMLT Enabled Community Member

**Comment by Connected57** [comment]
Awesome! Thanks for the quick reply and I appreciate all of the work that you do for our fellowship!!

Kind regards,
Aaron H.


________________________________

**Comment by Connected57** [comment]
Hey Patrick,

I hope you are doing well!


I was told by one of my fellow Public Relations committee members that the SPAD<https://spadna.org> website is now up and running and I was wondering if you had any timeline for the SPAD plugin release?


Kind regards,
Aaron H

________________________________

**Comment by pjaudiomv** [comment]
There is a new plugin that can be downloaded here https://github.com/bmlt-enabled/fetch-spad/releases/download/1.0.0/fetch-spad.zip I submitted it to Wordpress but that can take a couple weeks

**Comment by Connected57** [comment]
Thanks for the quick response!

Does that mean I can't use the plugin on my areas website until WordPress approves the plugin?


Kind regards,
Aaron H

________________________________

**Comment by pjaudiomv** [comment]
No you just have to install it from that zip

**Comment by Connected57** [comment]
Perfect. Thank you so much for your service! I will shoot you a link when I have it up on our website.

AH

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Connected57** [comment]
Hey Patrick,

Just wanted to let you know that I was able to install the plugin and add the SPAD short code to our website. Check it out here under JFT. https://naventuracounty.com/

Kind regards,
Aaron H
Gold Coast Area Webmaster
________________________________

**Comment by pjaudiomv** [comment]
Awesome looks great!

**Comment by pjaudiomv** [comment]
I am closing this out as fetch spad is now released in wordpress plugin repository https://wordpress.org/plugins/fetch-spad/
