### ISSUE TITLE
Translation bug (Raw html)

### ISSUE THREAD

**Issue by Klodd65** [bmlt-enabled/fetch-jft#26]
The Just for today page has not working on french website, today and on Yap.

https://na-outaouais.org/juste-pour-aujourdhui/

https://csr.naquebec.org/juste-pour-aujourdhui/

https://jpa.narcotiquesanonymes.org/

**Comment by pjaudiomv** [comment]
I think this is an issue with their server. I've noticed that their server is extremely slow, sometimes taking up to 30sec to return a response.

**Comment by Klodd65** [comment]
I will try to reach them.  This is not easy but some of them have an activitie with us in Zoom.
